<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' - Page {page}' => ' - Страница {page}',
    'Added by extension' => 'Добавлен модулем',
    'Allow Parallel Run' => '',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Attribute name' => 'Имя атрибута',
    'Attributes' => 'Атрибуты',
    'Backend menu items' => 'Меню админки',
    'BackendMenu' => 'Меню админки',
    'Backend menu' => 'Меню админки',
    'Class Name' => 'Название класса',
    'Class name' => 'Название класса',
    'Content' => 'Контент',
    'Context' => 'Контекст',
    'Context ID' => '',
    'Contexts' => 'Контексты',
    'Country Languages' => 'Языки страны',
    'Conutry Language' => 'Язык страны',
    'Create' => 'Создать',
    'Create Product' => 'Создать продукт',
    'Create Thing' => '',
    'Delete' => 'Удалить',
    'Demo site for yii2-data-structure-tools' => '',
    'Edit' => 'Редактировать',
    'Edit backend menu item' => 'Редактировать элемент меню',
    'Email Notification' => '',
    'Entity Dependent' => '',
    'Group Notifications' => '',
    'Hint' => '',
    'Home' => '',
    'ID' => '',
    'Icon' => 'Иконка',
    'Is Layout' => '',
    'Key' => 'Ключ',
    'Languages' => 'Языки',
    'Layout' => 'Слой',
    'Manage property groups' => '',
    'Mask' => 'Маска',
    'Masked input settings' => '',
    'Monster' => 'Монстер',
    'More' => 'Больше',
    'Name' => 'Название',
    'New item' => 'Новый пункт',
    'Not selected' => 'Не выбран',
    'Notify Initiator' => '',
    'Notify Roles' => '',
    'Object has been removed' => '',
    'Object has not been removed' => '',
    'Open gallery' => 'Открыть галлерею',
    'Order desc' => '',
    'Parent ID' => 'Родитель',
    'Price' => 'Цена',
    'Products' => 'Продукты',
    'Prop' => '',
    'Property' => '',
    'Property Group' => '',
    'Rbac role' => 'Rbac роль',
    'Related entity settings' => '',
    'Route' => 'Путь',
    'Run Last Command Only' => '',
    'Set correct property handler' => '',
    'Sort Order' => 'Сортировка',
    'Sort Order Group Properties' => '',
    'Sort Order Property Groups' => '',
    'Sort order' => 'Сортировка',
    'Template' => 'Шаблон',
    'Template ID' => 'ID Шаблона',
    'Things' => '',
    'This is an example application showing main package features.' => '',
    'Translation Category' => 'Категория переводов',
    'Type for search ...' => '',
    'Unknown' => '',
    'Update' => 'Редактировать',
    'Update {modelClass}: ' => '{modelClass} изменен',
    'Save {modelClass}' => '{modelClass} сохранен',
    'Value' => 'Значение',
    'You can switch languages in top menu' => '',
    'You cannot update or delete system handlers' => '',
    'You should add TagDependencyTrait to your model class {class}' => '',
    'You should enter correct settings' => 'Вы должны ввести правильные настройки',
    'and' => 'и',
    'here' => 'здесь',
    'Extensions' => 'Расширения',
    'Users' => 'Пользователи',
    '{model} with id :\'{id}\' not found!' => '{model} с id :\'{id}\' не найдена!',
];
